# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [ "psmouse.synaptics_intertouch=0" ];
  boot.extraModulePackages = [ ];

  hardware = {
    cpu.intel.updateMicrocode = true;
    bluetooth.enable = true;
    pulseaudio.package = pkgs.pulseaudioFull;
  };
  
  # Make suspend to ram work.
  services.udev.extraRules =
  ''
    #ACTION=="add", SUBSYSTEM=="usb", TEST=="power/control" ATTR{power/control}="auto"
    ACTION=="add", SUBSYSTEM=="pci", DRIVER=="xhci_hcd", TEST=="power/wakeup" ATTR{power/wakeup}="disabled"
  '';

  services.udev.extraHwdb =
  ''
    libinput:name:*TrackPoint*                                                      
     LIBINPUT_ATTR_TRACKPOINT_RANGE=5
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/aa5aed15-618a-4246-99e7-d764388d61f6";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  swapDevices = [ { device = "/dev/sda2";
                    randomEncryption = {enable = true;
                                        cipher = "aes-xts-plain64";
                                       };
                  }
                ];

  boot.initrd.luks.devices."nixroot".device = "/dev/disk/by-uuid/527439dc-2e4f-4f1c-80e6-868178da99a8";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/aa5aed15-618a-4246-99e7-d764388d61f6";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/aa5aed15-618a-4246-99e7-d764388d61f6";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/920A-2CF3";
      fsType = "vfat";
    };

  nix.maxJobs = lib.mkDefault 4;
  #powerManagement.cpuFreqGovernor = "powersave";
}
